name = "Moose"
license = "MIT"
licenselink = "https://github.com/mvuijlst/moose/blob/master/LICENSE"
description = "Theme for Moose Dept. personal site"
homepage = "http://users.ugent.be/~mvujlst"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Michel Vuijlsteke"
  homepage = "https://blog.zog.org"

